# Generated by Django 2.0.1 on 2019-02-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
